### ISSUE TITLE
Investigate why some examples don't render/behave as expected

### ISSUE THREAD

**Issue by pausz** [sciris/scirisweb#47]
Ran the following cases under `examples/':
- hellograph
- py-shiny
- py-shiny2

They don't render properly. Maybe matplotlib backend?, browser issues?   

![scirisweb_examples_hellograph](https://user-images.githubusercontent.com/1563810/165457859-ff5718ad-22d3-49bb-ae66-fe7cda385ee0.png)
![run_examples_py-shiny2](https://user-images.githubusercontent.com/1563810/165457870-1bff714f-7ab7-4ad8-8b01-5f9c7e516f87.png)

Basic env info:
- Python 3.9.12
- matplotlib 3.5.1
- Firefox 99.0 
- OS Ubuntu 20.04

**Comment by pausz** [comment]
py-shiny example may be due to incompatibility with recent version of vue.js -- https://unpkg.com/vue currently points to https://unpkg.com/vue@3.2.33/dist/vue.global.js
![Screenshot from 2022-05-16 20-04-43](https://user-images.githubusercontent.com/1563810/168569950-94bc4b8d-67ca-42d0-aa78-49e815fe4bdd.png)
n

**Comment by cliffckerr** [comment]
Fixed
