### ISSUE TITLE
Remove return None from intialisation methods 

### ISSUE THREAD

**Issue by pausz** [sciris/scirisweb#49]
Remove `return None` statements from several class `__init__` method 

+ [ ]  [sw_app.py: class ScirisApp](https://github.com/sciris/scirisweb/blob/develop/scirisweb/sw_app.py#L173)
+ [ ]  [sw_task.py: class Task](https://github.com/sciris/scirisweb/blob/develop/scirisweb/sw_tasks.py#L73)
+ [ ]  [sw_users.py: class User](https://github.com/sciris/scirisweb/blob/develop/scirisweb/sw_users.py#L70)
+ [ ]  [sw_datastore.py: class Blob](https://github.com/sciris/scirisweb/blob/develop/scirisweb/sw_datastore.py)
+ [ ] [sw_datastore.py: class DataStoreSetting] 
+ [ ] [sw_datastore.py: class BaseDataStore] 
+ [ ] [sw_datastore.py: class RedisDataStore] 
+ [ ] [sw_datastore.py: class SQLDataStore] 
+ [ ] [sw_datastore.py: class FileDataStore] 
+ [ ] [sw_datastore.py: class DataDir]

**Comment by cliffckerr** [comment]
Done
