### ISSUE TITLE
Set type of error expected in try/expect blocks

### ISSUE THREAD

**Issue by pausz** [sciris/scirisweb#50]
There are some `except` clauses without an explicit type of error. Not sure if bare except behaviour was the desired behaviour -- from context doesn't seem like it. May also be useful to print some sort of message in except block.   

+ [ ] [`sw_app.py _do_RPC()`](https://github.com/sciris/scirisweb/blob/develop/scirisweb/sw_app.py#L411)  (eg, json decode error, maybe related to #37?) 
+ [ ] [`sw_datastore.py get()`](https://github.com/sciris/scirisweb/blob/develop/scirisweb/sw_datastore.py#L335) 
+ [ ] [`sw_datastore.py DataDir`](https://github.com/sciris/scirisweb/blob/develop/scirisweb/sw_datastore.py#L892)
+ [ ] [`sw_server.py` imports](https://github.com/sciris/scirisweb/blob/develop/scirisweb/sw_server.py#L16)  (eg, import error)
+ [ ] [`sw_server.py` browser](https://github.com/sciris/scirisweb/blob/develop/scirisweb/sw_server.py#L82) (eg, webbrowser error)

**Comment by cliffckerr** [comment]
Done
