### ISSUE TITLE
Deprecation in werkzeug

### ISSUE THREAD

**Issue by cliffckerr** [sciris/scirisweb#52]
```py
    from .sw_app       import * # analysis:ignore
    from werkzeug.serving import run_with_reloader
ImportError: cannot import name 'run_with_reloader' from 'werkzeug.serving' 
```
Werkzeug==2.0.1

**Comment by RomeshA** [comment]
@cliffckerr I'm hitting this one too now. As a short term fix, maybe it's OK to replace it with `from werkzeug._reloader import run_with_reloader`. In the longer term this function shouldn't be used at all, but a different solution for twisted+autoreload will be needed

**Comment by RomeshA** [comment]
Werkzeug suggests using `werkzeug.run_simple(..., use_reloader=True)`

**Comment by cliffckerr** [comment]
Done
